"""Add fps and resolution column to table camera

Revision ID: 0ddab9f9ce7a
Revises: 
Create Date: 2025-12-25 10:35:34.337281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ddab9f9ce7a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('fps', sa.Integer(), nullable=True))
    op.add_column('cameras', sa.Column('resolution', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cameras', 'resolution')
    op.drop_column('cameras', 'fps')
    # ### end Alembic commands ###
